PagWeb/PagWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authApp.urls')),
    path('', include('webApp.urls')),
    path('about/', include('serviceApp.urls')),
    path('market/', include('tiendaApp.urls')),
    path('cart/', include('carroApp.urls')),
    path('blog/', include('blogApp.urls')),
    path('contact/', include('contactApp.urls')),
    path('pedidos/', include('pedidosApp.urls')),
]

PagWeb/carroApp/urls.py
from django.urls import path
from . import views

app_name = 'carro'

urlpatterns = [
    path('add/<int:product_id>', views.add_product, name='agregar'),
    path('del/<int:product_id>', views.del_product, name='eliminar'),
    path('sub/<int:product_id>', views.sub_product, name='restar'),
    path('empty/', views.empty_cart, name='limpiar'),
]

PagWeb/tiendaApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.market, name='Market'),
]

PagWeb/tiendaApp/models.py
from tkinter import image_names
from django.db import models
from matplotlib import image


class Category(models.Model):
    name = models.CharField(verbose_name='Título', max_length=50)
    created = models.DateTimeField(verbose_name='Creado', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Actualizado', auto_now_add=True)
    
    # model meta options
    class Meta:
        verbose_name='categoría'
        verbose_name_plural='categorías'
    
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(verbose_name='Título', max_length=50)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categorias')
    image = models.ImageField(verbose_name='Imagen', upload_to='tiendaApp', null=True, blank=True)
    price = models.FloatField(verbose_name='Precio')
    availability = models.BooleanField(verbose_name='Disponibilidad', default=True)
    created = models.DateTimeField(verbose_name='Creado', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Actualizado', auto_now_add=True)

    class Meta:
        verbose_name='producto'
        verbose_name_plural='productos'

    def __str__(self):
        return self.name

PagWeb/carroApp/views.py
from django.shortcuts import render, redirect
from .carro import Cart
from tiendaApp.models import Product


def add_product(req, product_id):
    carro = Cart(req)
    product = Product.objects.get(id=product_id)
    carro.addProduct(product=product)
    return redirect('Market')

def del_product(req, product_id):
    carro = Cart(req)
    product = Product.objects.get(id=product_id)
    carro.delProduct(product=product)
    return redirect('Market')

def sub_product(req, product_id):
    carro = Cart(req)
    product = Product.objects.get(id=product_id)
    carro.subProduct(product=product)
    return redirect('Market')

def empty_cart(req):
    carro = Cart(req)
    carro.emptyCart()
    return redirect('Market')

PagWeb/tiendaApp/views.py
from django.shortcuts import render
from .models import Product


def market(req):
    products = Product.objects.all()
    return render(req, 'tiendaApp/market.html', {'products': products})

PagWeb/tiendaApp/templates/carroApp/widget.html
<table class="table table-bordered" style="color:black;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                <i class="bi-cart-fill me-1"></i>
                Carro compras
                <span class="badge bg-dark text-white ms-1 rounded-pill">{{ total_cant }}</span>
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cant</th>
            <th>Precio</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
            <tr class="text-center">
                <td>{{ value.product_name }}</td>
                <td>{{ value.product_cant }}</td>
                <td>
                    <a class="btn btn-outline-dark mt-auto" href="{% url 'carro:restar' value.product_id %}">-</a>
                    <a class="btn btn-outline-dark mt-auto" href="{% url 'carro:agregar' value.product_id %}">+</a>
                    ${{ value.product_price }}
                </td>
            </tr>

            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">No se han agregado items</div>

                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr><td colspan="3">Total: {{ total_cart }}</td></tr>
        
        {% if request.session.carro.items %}
        <tr><td colspan="3" style="text-align: center;">
            <a href="{% url 'ProcesarPedido' %}" class="btn btn-outline-dark bg-dark bg-opacity-25 mt-auto">Comprar</a>
        </td></tr>
        {% endif %}

        <tr><td colspan="3">
            {% if messages %}
            {% for msg in messages %}
                <div class="alert text-center">{{ msg }}</div>
            {% endfor %}
            {% endif %}
        </td></tr>

    </tfoot>

    
</table>